# Generated by Django 4.1 on 2022-12-03 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=20, verbose_name='Nombre')),
                ('apellido', models.CharField(blank=True, max_length=20, verbose_name='apellido')),
                ('fecha_nacimiento', models.CharField(blank=True, max_length=20, verbose_name='Fecha de Nacimiento')),
                ('sueldo_mensual', models.CharField(blank=True, max_length=20, verbose_name='Sueldo Mensual')),
            ],
        ),
    ]
