# Generated by Django 4.1 on 2022-12-03 17:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobbys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby', models.CharField(max_length=25, verbose_name='Hobby')),
            ],
        ),
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pelicula', models.CharField(max_length=25, verbose_name='Pelicula Favorita')),
                ('recaudacion', models.CharField(blank=True, max_length=25, verbose_name='Recaudacion')),
                ('presupuesto', models.CharField(blank=True, max_length=25, verbose_name='Presupuesto')),
            ],
        ),
        migrations.AddField(
            model_name='usuarios',
            name='dni',
            field=models.CharField(blank=True, max_length=20, verbose_name='DNI'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='hobby',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='registros.hobbys'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='pelicula_favorita',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='registros.peliculas'),
            preserve_default=False,
        ),
    ]
